/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Personal_Schedule_Management;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;

import java.io.File;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import java.sql.Blob;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Forgot_Form extends javax.swing.JFrame {

    private Font Arian;

    /**
     * Creates new form Forgot_Form
     */
    public Forgot_Form() {
        initComponents();
        Border jlabel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_cancel.setBorder(jlabel_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_main = new javax.swing.JPanel();
        jPanel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_cancel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_btnBack = new javax.swing.JButton();
        jButton_btnRec = new javax.swing.JButton();
        jTextField_password = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jTextField_fullname = new javax.swing.JTextField();
        jTextField_question = new javax.swing.JTextField();
        jTextField_answer = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_main.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(153, 153, 153)));
        jPanel_main.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_main.setMinimumSize(new java.awt.Dimension(400, 550));
        jPanel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_header.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recovery");

        jLabel_cancel.setFont(new java.awt.Font("Gadugi", 1, 25)); // NOI18N
        jLabel_cancel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_cancel.setText("x");
        jLabel_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_headerLayout = new javax.swing.GroupLayout(jPanel_header);
        jPanel_header.setLayout(jPanel_headerLayout);
        jPanel_headerLayout.setHorizontalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_headerLayout.createSequentialGroup()
                .addGap(0, 124, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jLabel_cancel))
        );
        jPanel_headerLayout.setVerticalGroup(
            jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_headerLayout.createSequentialGroup()
                .addGroup(jPanel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_headerLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel_main.add(jPanel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password:");
        jPanel_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Username:");
        jPanel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fullname:");
        jPanel_main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Question:");
        jPanel_main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Answer:");
        jPanel_main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jButton_btnBack.setBackground(new java.awt.Color(255, 0, 0));
        jButton_btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_btnBack.setForeground(new java.awt.Color(255, 255, 255));
        jButton_btnBack.setText("Go back");
        jButton_btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_btnBackMouseExited(evt);
            }
        });
        jButton_btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_btnBackActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 140, 30));

        jButton_btnRec.setBackground(new java.awt.Color(0, 51, 204));
        jButton_btnRec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_btnRec.setForeground(new java.awt.Color(255, 255, 255));
        jButton_btnRec.setText("Recover");
        jButton_btnRec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_btnRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_btnRecMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_btnRecMouseExited(evt);
            }
        });
        jButton_btnRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_btnRecActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_btnRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 140, 30));

        jTextField_password.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_password.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_passwordKeyTyped(evt);
            }
        });
        jPanel_main.add(jTextField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 330, 40));

        jTextField_username.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_username.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(155, 155, 155));
        jTextField_username.setText("         Enter Username to Search");
        jTextField_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyPressed(evt);
            }
        });
        jPanel_main.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 330, 40));

        jTextField_fullname.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_fullname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_fullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField_fullname.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField_fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_fullnameKeyTyped(evt);
            }
        });
        jPanel_main.add(jTextField_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 330, 40));

        jTextField_question.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_question.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_question.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField_question.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_questionKeyTyped(evt);
            }
        });
        jPanel_main.add(jTextField_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 330, 40));

        jTextField_answer.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_answer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField_answer.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel_main.add(jTextField_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_cancelMouseClicked

    private void jButton_btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_btnBackActionPerformed
        // TODO add your handling code here:
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_btnBackActionPerformed

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
        // TODO add your handling code here:
        if(jTextField_username.getText().trim().equals("Enter Username to Search")){
            jTextField_username.setText("");
            JOptionPane.showMessageDialog(this, "Please enter your username and press enter");
        }
        jTextField_username.setForeground(Color.black);
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
        if(jTextField_username.getText().trim().equals("Enter Username to Search")){
            jTextField_username.setText("        Enter Username to Search");
            jTextField_fullname.setText("");
            jTextField_question.setText("");
            jTextField_password.setText("");
            jTextField_username.setForeground(new Color(155,155,155));
        }
        
        
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jButton_btnRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_btnRecActionPerformed
        // TODO add your handling code here:
        String ans = jTextField_answer.getText();
        if(ans.equals("")){
            JOptionPane.showMessageDialog(this, "Please fill the answer to retrieve Password");
        }
        else{
            PreparedStatement ps;
            ResultSet rs;
            String query="SELECT * FROM `users` WHERE `phone`=? AND `username`=?";
            
            try {
                ps = My_CNX.getConnection().prepareStatement(query);
                ps.setString(1, ans);
                ps.setString(2, jTextField_username.getText());
                rs=ps.executeQuery();
                if(rs.next()){
                    jTextField_password.setText("You password is " + rs.getString("password"));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Your answer is not true!!!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Forgot_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_btnRecActionPerformed

    private void jTextField_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyPressed
        // TODO add your handling code here:
        //chon den khi nhan Enter
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            PreparedStatement ps;
            ResultSet rs;
        
            String user = jTextField_username.getText();
            if(user.trim().equals("")){
                JOptionPane.showMessageDialog(this, "Enter your username");
            }
            else{
                String query = "SELECT * FROM `users` WHERE `username`=?";
                try {
                    ps = My_CNX.getConnection().prepareStatement(query);
                    ps.setString(1, user);
                    rs = ps.executeQuery();
                    if(rs.next()){
                        jTextField_fullname.setText(" "+rs.getString("full_name"));
                        jTextField_question.setText(" What's your phone number?");
                    
                        
                
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Your account does not exist");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Forgot_Form.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
            
        
            
        }
        
    }//GEN-LAST:event_jTextField_usernameKeyPressed

    private void jTextField_fullnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_fullnameKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())||Character.isDigit(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Do not type in Fullname and Question", "Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextField_fullnameKeyTyped

    private void jTextField_questionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_questionKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())||Character.isDigit(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Do not type in Fullname and Question", "Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextField_questionKeyTyped

    private void jTextField_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_passwordKeyTyped
        // TODO add your handling code here:
        if(Character.isDigit(evt.getKeyChar())||!Character.isDigit(evt.getKeyChar())){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Do not type in Password", "Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextField_passwordKeyTyped

    private void jButton_btnRecMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_btnRecMouseEntered
        // TODO add your handling code here:
        jButton_btnRec.setBackground(new Color(0,30,150));
    }//GEN-LAST:event_jButton_btnRecMouseEntered

    private void jButton_btnRecMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_btnRecMouseExited
        // TODO add your handling code here:
        jButton_btnRec.setBackground(new Color(0,51,204));
    }//GEN-LAST:event_jButton_btnRecMouseExited

    private void jButton_btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_btnBackMouseExited
        // TODO add your handling code here:
        jButton_btnBack.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jButton_btnBackMouseExited

    private void jButton_btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_btnBackMouseEntered
        // TODO add your handling code here:
        jButton_btnBack.setBackground(new Color(200,51,0));
    }//GEN-LAST:event_jButton_btnBackMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_btnBack;
    private javax.swing.JButton jButton_btnRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_cancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_header;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JTextField jTextField_answer;
    private javax.swing.JTextField jTextField_fullname;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_question;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
