/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Personal_Schedule_Management;

import java.awt.Color;
import java.awt.image.BufferedImage;

import java.io.File;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import java.sql.Blob;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Main_Form
     */
    public Main_Form() {
        initComponents();
        try {
            BufferedImage image = ImageIO.read(new File("logoPro.png"));//file anh luu ngoai file image
            int x = jLabel_Logo.getSize().width;
            int y = jLabel_Logo.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_Logo.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("icons_circled_s.png"));//file anh luu ngoai file image
            int x = jLabel_Logo_S_Cicle.getSize().width;
            int y = jLabel_Logo_S_Cicle.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_Logo_S_Cicle.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("buttons_blue.png"));//file anh luu ngoai file image
            int x = jLabel_button_login.getSize().width;
            int y = jLabel_button_login.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_login.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("logoPro.png"));//file anh luu ngoai file image
            int x = jLabel_button_circle_login.getSize().width;
            int y = jLabel_button_circle_login.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_circle_login.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("buttons_red.png"));//file anh luu ngoai file image
            int x = jLabel_button_signup.getSize().width;
            int y = jLabel_button_signup.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_signup.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("logoPro.png"));//file anh luu ngoai file image
            int x = jLabel_button_circle_signup.getSize().width;
            int y = jLabel_button_circle_signup.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_circle_signup.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            BufferedImage image = ImageIO.read(new File("minimize_button_blue.png"));//file anh luu ngoai file image
            int x = jLabel_minimize.getSize().width;
            int y = jLabel_minimize.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_minimize.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_main = new javax.swing.JPanel();
        jLabel_Logo_S_Cicle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Logo = new javax.swing.JLabel();
        jLabel_management = new javax.swing.JLabel();
        jLabel_button_circle_login = new javax.swing.JLabel();
        jLabel_login = new javax.swing.JLabel();
        jLabel_button_login = new javax.swing.JLabel();
        jLabel_button_circle_signup = new javax.swing.JLabel();
        jLabel_signup = new javax.swing.JLabel();
        jLabel_button_signup = new javax.swing.JLabel();
        jLabel_title = new javax.swing.JLabel();
        jLabel_cancel = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(737, 472));
        setUndecorated(true);

        jPanel_main.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/image/cancel_icon.png")))); // NOI18N
        jPanel_main.setMinimumSize(new java.awt.Dimension(737, 472));
        jPanel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Logo_S_Cicle.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Logo_S_Cicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons_circled_s.png"))); // NOI18N
        jLabel_Logo_S_Cicle.setText("jLabel2");
        jPanel_main.add(jLabel_Logo_S_Cicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 50, 40));
        jLabel3.setText("chedule");
        jPanel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 125, 310, 80));

        jLabel2.setFont(new java.awt.Font(".VnBahamasB", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 110, 180));
        jLabel2.setText("ersonal");
        jPanel_main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 340, 80));

        jLabel_Logo.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_Logo.setText("jLabel2");
        jPanel_main.add(jLabel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 10, 90, 90));

        jLabel_management.setFont(new java.awt.Font(".VnBahamasB", 1, 90)); // NOI18N
        jLabel_management.setForeground(new java.awt.Color(247, 202, 24));
        jLabel_management.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_management.setText("MANAGEMENT");
        jPanel_main.add(jLabel_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 660, 120));

        jLabel_button_circle_login.setText("jLabel5");
        jPanel_main.add(jLabel_button_circle_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 40, 39));

        jLabel_login.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_login.setText("Login");
        jLabel_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseExited(evt);
            }
        });
        jPanel_main.add(jLabel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 150, 40));

        jLabel_button_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_button_login.setText("jLabel5");
        jLabel_button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_main.add(jLabel_button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 150, 40));

        jLabel_button_circle_signup.setText("jLabel5");
        jPanel_main.add(jLabel_button_circle_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 40, 39));

        jLabel_signup.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel_signup.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_signup.setText("Sign up");
        jLabel_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_signupMouseExited(evt);
            }
        });
        jPanel_main.add(jLabel_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 40));

        jLabel_button_signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_button_signup.setText("jLabel5");
        jLabel_button_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_main.add(jLabel_button_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 40));

        jLabel_title.setFont(new java.awt.Font(".VnCommercial Script", 1, 36)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(255, 204, 51));
        jLabel_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_title.setText("Effective solution for personal management");
        jPanel_main.add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 550, -1));

        jLabel_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel_icon.png"))); // NOI18N
        jLabel_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseExited(evt);
            }
        });
        jPanel_main.add(jLabel_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel_minimize.setText("jLabel1");
        jLabel_minimize.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });
        jPanel_main.add(jLabel_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 24, 24));

        jLabel_background.setBackground(new java.awt.Color(255, 153, 153));
        jLabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        jLabel_background.setText("jLabel1");
        jPanel_main.add(jLabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 733, 468));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseEntered
        // TODO add your handling code here:
        jLabel_login.setForeground(Color.red);
        try {
            BufferedImage image = ImageIO.read(new File("buttons_green.png"));//file anh luu ngoai file image
            int x = jLabel_button_login.getSize().width;
            int y = jLabel_button_login.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_login.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_loginMouseEntered

    private void jLabel_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseExited
        // TODO add your handling code here:
        jLabel_login.setForeground(Color.white);
        try {
            BufferedImage image = ImageIO.read(new File("buttons_blue.png"));//file anh luu ngoai file image
            int x = jLabel_button_login.getSize().width;
            int y = jLabel_button_login.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_login.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_loginMouseExited

    private void jLabel_signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signupMouseExited
        // TODO add your handling code here:
        jLabel_signup.setForeground(Color.white);
        try {
            BufferedImage image = ImageIO.read(new File("buttons_red.png"));//file anh luu ngoai file image
            int x = jLabel_button_signup.getSize().width;
            int y = jLabel_button_signup.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_signup.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_signupMouseExited

    private void jLabel_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signupMouseEntered
        // TODO add your handling code here:
        jLabel_signup.setForeground(new Color(37, 116, 169));
        try {
            BufferedImage image = ImageIO.read(new File("buttons_orange.png"));//file anh luu ngoai file image
            int x = jLabel_button_signup.getSize().width;
            int y = jLabel_button_signup.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_button_signup.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_signupMouseEntered

    private void jLabel_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signupMouseClicked
        // TODO add your handling code here:
        Register_Form rf = new Register_Form();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jLabel_signupMouseClicked

    private void jLabel_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseClicked
        // TODO add your handling code here:
        Login_Form lf = new Login_Form();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_loginMouseClicked

    private void jLabel_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseEntered
        // TODO add your handling code here:
        try {
            BufferedImage image = ImageIO.read(new File("cancel_orange.png"));//file anh luu ngoai file image
            int x = jLabel_cancel.getSize().width;
            int y = jLabel_cancel.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_cancel.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel_cancelMouseEntered

    private void jLabel_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseExited
        // TODO add your handling code here:
        ImageIcon image = new ImageIcon("cancel_icon.png");
        jLabel_cancel.setIcon(image);
    }//GEN-LAST:event_jLabel_cancelMouseExited

    private void jLabel_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel_cancelMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        // TODO add your handling code here:
        try {
            BufferedImage image = ImageIO.read(new File("minimize_button_orange.png"));//file anh luu ngoai file image
            int x = jLabel_minimize.getSize().width;
            int y = jLabel_minimize.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_minimize.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        // TODO add your handling code here:
        try {
            BufferedImage image = ImageIO.read(new File("minimize_button_blue.png"));//file anh luu ngoai file image
            int x = jLabel_minimize.getSize().width;
            int y = jLabel_minimize.getSize().height;
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jLabel_minimize.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main_Form mf = new Main_Form();
                mf.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Logo;
    private javax.swing.JLabel jLabel_Logo_S_Cicle;
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_button_circle_login;
    private javax.swing.JLabel jLabel_button_circle_signup;
    private javax.swing.JLabel jLabel_button_login;
    private javax.swing.JLabel jLabel_button_signup;
    private javax.swing.JLabel jLabel_cancel;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_management;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_signup;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel_main;
    // End of variables declaration//GEN-END:variables
}
