/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Personal_Schedule_Management;
import java.io.File;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import java.sql.Blob;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class Profile_Form extends javax.swing.JFrame {

    /**
     * Creates new form Profile_Form
     */
    String username, path;
    
    public Profile_Form() {
        initComponents();
        
        
    }
    public Profile_Form(String username, String path, String fullname, String id, Date date, String phone, String fsaying) throws IOException{
        initComponents();
        
        PreparedStatement ps;
        ResultSet rs;
        
        String query="SELECT * FROM `users` WHERE `username`=?";
            
            try {
                ps = My_CNX.getConnection().prepareStatement(query);
                ps.setString(1, username);
                this.username = username;
                rs=ps.executeQuery();
                if(rs.next()){
                    if(path==null){
                        jLabel_image.setText("No have image");
                    }
                    else{
                        try {
                            BufferedImage image = ImageIO.read(new File(path));
                            this.path = path;
                            int x = jLabel_image.getSize().width;
                            int y = jLabel_image.getSize().height;
                            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
                            jLabel_image.setIcon(icon);
            
            
                        }
                        catch (IOException ex) {
                            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
            
                        }
                    }
                    jTextField_Fullnamep.setText(rs.getString(2));
                    jTextField_phonep.setText(rs.getString(5));
                    if(rs.getString(10)==null){
                        jTextField_idp.setText("");
                    }
                    else{
                        jTextField_idp.setText(rs.getString(10));
                    }
                    
                    if(rs.getDate(8)==null){
                        jDateChooser_dateofbirthp.setDate(null);
                    }
                    else{
                        jDateChooser_dateofbirthp.setDate(rs.getDate(8));
                    }
                    if(rs.getString(9)==null){
                        jTextArea_fsayingp.setText("");
                    }
                    else{
                        jTextArea_fsayingp.setText(rs.getString(9));
                    }
                }
                        
                    
                
                
                    
                
            } catch (SQLException ex) {
                Logger.getLogger(Forgot_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel_background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Fullnamep = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_dateofbirthp = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextField_idp = new javax.swing.JTextField();
        jButton_return = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_fsayingp = new javax.swing.JTextArea();
        jTextField_phonep = new javax.swing.JTextField();

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Full Name:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_background.setBackground(new java.awt.Color(255, 204, 255));
        jPanel_background.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel_background.setForeground(new java.awt.Color(255, 153, 153));
        jPanel_background.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel_background.setMinimumSize(new java.awt.Dimension(635, 576));
        jPanel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel_background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 200, 50));

        jLabel_image.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_image.setText("jLabel2");
        jLabel_image.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 255)));
        jPanel_background.add(jLabel_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, 420));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Full Name:");
        jPanel_background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("ID:");
        jPanel_background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Favorite saying:");
        jPanel_background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jTextField_Fullnamep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_Fullnamep.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 0)));
        jTextField_Fullnamep.setMinimumSize(new java.awt.Dimension(64, 22));
        jPanel_background.add(jTextField_Fullnamep, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 240, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Phone:");
        jPanel_background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jDateChooser_dateofbirthp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDateChooser_dateofbirthp.setDateFormatString("dd-MM-yyyy");
        jPanel_background.add(jDateChooser_dateofbirthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 262, 200, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Date of birth:");
        jPanel_background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jTextField_idp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_idp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 0)));
        jTextField_idp.setMinimumSize(new java.awt.Dimension(64, 22));
        jPanel_background.add(jTextField_idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 300, -1));

        jButton_return.setBackground(new java.awt.Color(255, 51, 51));
        jButton_return.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_return.setText("Return");
        jButton_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_returnMouseClicked(evt);
            }
        });
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });
        jPanel_background.add(jButton_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 190, 30));

        jButton_update.setBackground(new java.awt.Color(51, 51, 255));
        jButton_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_update.setText("Update");
        jButton_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel_background.add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 190, 30));

        jTextArea_fsayingp.setColumns(20);
        jTextArea_fsayingp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_fsayingp.setRows(5);
        jScrollPane2.setViewportView(jTextArea_fsayingp);

        jPanel_background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 310, 160));

        jTextField_phonep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField_phonep.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 0, 0)));
        jTextField_phonep.setMinimumSize(new java.awt.Dimension(64, 22));
        jPanel_background.add(jTextField_phonep, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_returnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_returnMouseClicked

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnActionPerformed
        try {
            // TODO add your handling code here:
            Menu_Form mf = new Menu_Form(jTextField_Fullnamep.getText(), username, path, jTextField_idp.getText(), jTextField_phonep.getText(), jDateChooser_dateofbirthp.getDate(), jTextArea_fsayingp.getText());
            mf.setVisible(true);
            mf.pack();
            mf.setLocationRelativeTo(this);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Profile_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_returnActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        String value1 = jTextField_Fullnamep.getText();
        String value2 = jTextField_idp.getText();
        String value3 = jTextField_phonep.getText();
        
        
        Date date = jDateChooser_dateofbirthp.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String value4 = sdf.format(date);
        
        String value5 = jTextArea_fsayingp.getText();
        
        int p = JOptionPane.showConfirmDialog(this, "Are you sure to update your profile","Update Record", JOptionPane.YES_NO_OPTION);
        if(p == JOptionPane.YES_OPTION){
            PreparedStatement ps;
            ResultSet rs;
            
            String query = "UPDATE `users` SET `full_name`='"+value1+"',`phone`='"+value3+"',`birthdate`='"+value4+"',`fsaying`='"+value5+"',`idstudent`='"+value2+"' WHERE `full_name`='"+value1+"'";
            
            try {
                ps = My_CNX.getConnection().prepareStatement(query);
                ps.execute();
                JOptionPane.showMessageDialog(this, "Upadate successfull");
            } catch (SQLException ex) {
                Logger.getLogger(Menu_Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
    }//GEN-LAST:event_jButton_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_return;
    private javax.swing.JButton jButton_update;
    private com.toedter.calendar.JDateChooser jDateChooser_dateofbirthp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_fsayingp;
    private javax.swing.JTextField jTextField_Fullnamep;
    private javax.swing.JTextField jTextField_idp;
    private javax.swing.JTextField jTextField_phonep;
    // End of variables declaration//GEN-END:variables
}
